#!/bin/bash
if [ $# -lt 1 ] || [ $1 = --help ]
then
    echo git annex copy all files under current directory to specified remote
    echo usage: $0 [remote]
    exit
fi

git annex find | sed  -e 's/.*/\"&\"/' | xargs git annex copy --to=$1
