#!/bin/bash
#
# Copyright (C) 2010,
#   Thomas Langewouters <thomas.langewouters@thouters.be>
# Based on the script svnvimdiff, written by
# Copyright (C) 2007,
#   Geoff Buchan	<geoffrey.buchan@gmail.com>
# Based on the script cvsvimdiff, written by
#   Stefano Zacchiroli	<zack@cs.unibo.it>
#   Enrico Tassi	<tassi@cs.unibo.it>
#
# This is free software, you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#
set -ex
vimdiff="vimdiff"
#suffix="vimgitdiff"
if [[ $1 == "-g" ]] ; then
  vimdiff="gvimdiff -f"
  shift 1
fi

if [[ $# -lt 0 || $1 == "--help" || $1 == "-h" ]] ; then
    echo "gitvimdiff - script to show git diff in vimdiff format in tabs"
    echo ""
    echo "gitvimdiff [options] file"
    echo ""
    echo "Option:"
    echo "-g    Use gvimdiff (graphical mode) instead of vimdiff"
    echo "All other options are passed to git diff"
    echo ""
    echo "If file is omitted it will cycle through all changed files in"
    echo "the current directory."
    exit 1
fi

# Assume the last argument is the filename.
# Save everything to pass to svn diff
if (( $# > 0 )) ; then
   shift_args=$(($# - 1))
else
   shift_args=$#
fi
TMP=$(mktemp -d /tmp/gitvimdiff.XXXX)
args=$*
shift "$shift_args"
files="$1"
#patch=$TMP/patch
script=$TMP/script
GITROOT=$(pwd)
while [[ ! -e $GITROOT/$1 ]]
do
    GITROOT=$(dirname "$GITROOT")
    if [ "$GITROOT" = "/" ]
    then
	break
    fi
done
if [ "$GITROOT" = "/" ]
then
    echo gitroot found! >/dev/stderr
    exit 0
fi

cd "$GITROOT"
if [ -z "$files" ] || ! [ -f "$files" ] ; then
    # No file given, so loop over all files svn st says have changed
    if [ -z "$args" ]; then
        files=$(git diff --name-only) 
    else
        files=$(git diff --name-only "$args")
    fi
    echo "Changed files: $files"

    if [ -z "$files" ] ; then
        echo "No changes to show"
        exit 1
    fi
fi

for new in $files
do
#Instead of [ -z $(foo | grep bar) ], use ! foo | grep -q bar . [SC2143]
    if ! file "$new" |grep -q text; 
    then
        #binary file
        true
    else
        orig=$TMP/$new
        mkdir -p "$(dirname "$orig")"
        git show HEAD:"$new" >"$orig"
        
        echo -e ":tabnew $orig\n:vert diffsplit $new" >> "$script"
    fi
done
$vimdiff -s "$script" commit.txt
#trap "rm -rf $TMP" EXIT
