#!/bin/bash
#
# Copyright (C) 2010,
#   Thomas Langewouters <thomas.langewouters@thouters.be>
# Based on the script svnvimdiff, written by
# Copyright (C) 2007,
#   Geoff Buchan	<geoffrey.buchan@gmail.com>
# Based on the script cvsvimdiff, written by
#   Stefano Zacchiroli	<zack@cs.unibo.it>
#   Enrico Tassi	<tassi@cs.unibo.it>
#
# This is free software, you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#
set -e
vimdiff="vimdiff"
#suffix="vimgitdiff"
if [[ $1 == "-g" ]] ; then
  vimdiff="gvimdiff -f"
  shift 1
fi

if [[ $# -lt 0 || $1 == "--help" || $1 == "-h" ]] ; then
    echo "westvimdiff - script to show git diff in vimdiff format in tabs"
    echo ""
    echo "westvimdiff [options] file"
    echo ""
    echo "Option:"
    echo "-g    Use gvimdiff (graphical mode) instead of vimdiff"
    echo "All other options are passed to git diff"
    echo ""
    echo "If file is omitted it will cycle through all changed files in"
    echo "the current directory."
    exit 1
fi

# Assume the last argument is the filename.
# Save everything to pass to svn diff
if (( $# > 0 )) ; then
   shift_args=$(($# - 1))
else
   shift_args=$#
fi
TMP=$(mktemp -d /tmp/westvimdiff.XXXX)
args=$*
shift "$shift_args"
files="$1"
#patch=$TMP/patch
script=$TMP/script
WESTROOT=$(pwd)
while [[ ! -e $WESTROOT/.west ]]
do
    WESTROOT=$(dirname "$WESTROOT")
    if [ "$WESTROOT" = "/" ]
    then
	break
    fi
done
if [ "$WESTROOT" = "/" ]
then
    echo WESTROOT not found! >/dev/stderr
    exit 0
fi

cd "$WESTROOT"
for WEST_MODULEDIR in $(west list -f "{path}")
do
    cd "${WESTROOT}/${WEST_MODULEDIR}"
    # No file given, so loop over all files svn st says have changed
    if [ -z "$args" ]; then
        files=$(git diff --name-only)
    else
        files=$(git diff --name-only "$args")
    fi

    for new in $files
    do
        echo $WEST_MODULEDIR/$new
    done
done

